### PR TITLE
update symbols

### PR DESCRIPTION
**Pull request by sdeffaux**

### CODE REVIEW

**Comment by scorpio810** [comment]
Conflicting files
elements/10_electric/10_allpole/140_connectors&plugs/20_socket_outlets/pc_mono2.elmt
elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant.elmt
elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant2.elmt
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21020.elmt
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21024.elmt
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21025.elmt
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/4AI.elmt
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/carte_rs232.elmt
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/facade_s500.elmt

**Comment by sdeffaux** [comment]
Je vois pas se qui cloche

**Comment by scorpio810** [comment]
[22:22:35] laurent@debian:~/Qet-svn/git/qet$ git checkout -b sdeffaux-master master
M       examples/industrial.qet
Basculement sur la nouvelle branche 'sdeffaux-master'
[22:24:14] laurent@debian:~/Qet-svn/git/qet$ git pull https://github.com/sdeffaux/qelectrotech-source-mirror.git master
remote: Enumerating objects: 388, done.
remote: Counting objects: 100% (388/388), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 232 (delta 184), reused 207 (delta 160), pack-reused 0
Réception d'objets: 100% (232/232), 123.12 Kio | 984.00 Kio/s, fait.
Résolution des deltas: 100% (184/184), complété avec 84 objets locaux.
Depuis https://github.com/sdeffaux/qelectrotech-source-mirror
 * branch                master     -> FETCH_HEAD
Fusion automatique de elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/facade_s500.elmt
CONFLIT (contenu) : Conflit de fusion dans elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/facade_s500.elmt
Fusion automatique de elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/carte_rs232.elmt
CONFLIT (contenu) : Conflit de fusion dans elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/carte_rs232.elmt
CONFLIT (modification/suppression) : elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/4AI.elmt supprimé dans 7a3307cebdd0cb4496e44af0e7bef19ef335bc10 et modifié dans HEAD. Version HEAD de elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/4AI.elmt laissée dans l'arbre.
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21025.elmt
Fusion automatique de elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21025.elmt
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21024.elmt
Fusion automatique de elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21024.elmt
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21020.elmt
Fusion automatique de elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21020.elmt
Suppression de elements/10_electric/10_allpole/395_electronics&semiconductors/24piezo/piezotransducer2.elmt
Suppression de elements/10_electric/10_allpole/395_electronics&semiconductors/24piezo/piezotransducer1.elmt
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant2.elmt
Fusion automatique de elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant2.elmt
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant.elmt
Fusion automatique de elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant.elmt
CONFLIT (ajout/ajout) : Conflit de fusion dans elements/10_electric/10_allpole/140_connectors&plugs/20_socket_outlets/pc_mono2.elmt
Fusion automatique de elements/10_electric/10_allpole/140_connectors&plugs/20_socket_outlets/pc_mono2.elmt
La fusion automatique a échoué ; réglez les conflits et validez le résultat.
[22:24:30] laurent@debian:~/Qet-svn/git/qet$ git checkout master
elements/10_electric/10_allpole/140_connectors&plugs/20_socket_outlets/pc_mono2.elmt: needs merge
elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant.elmt: needs merge
elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant2.elmt: needs merge
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21020.elmt: needs merge
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21024.elmt: needs merge
elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21025.elmt: needs merge
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/4AI.elmt: needs merge
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/carte_rs232.elmt: needs merge
elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/facade_s500.elmt: needs merge
error: vous devez d'abord résoudre votre index courant
[22:25:28] laurent@debian:~/Qet-svn/git/qet$ git merge --no-ff sdeffaux-master
error: Impossible de fusionner car vous avez des fichiers non fusionnés.
astuce: Corrigez-les puis lancez 'git add/rm <fichier>'
astuce: si nécessaire pour marquer la résolution et valider.
fatal: Abandon à cause de conflit non résolu.
[22:25:54] laurent@debian:~/Qet-svn/git/qet$ git add -A
[22:28:11] laurent@debian:~/Qet-svn/git/qet$ git status
Sur la branche sdeffaux-master
Tous les conflits sont réglés mais la fusion n'est pas terminée.
  (utilisez "git commit" pour terminer la fusion)

Modifications qui seront validées :
        nouveau fichier : 14.patch
        modifié :         elements/10_electric/10_allpole/140_connectors&plugs/20_socket_outlets/pc_mono2.elmt
        modifié :         elements/10_electric/10_allpole/200_fuses&protective_gears/20_disconnecting_switches/interrupteur_sectionneur_biphase.elmt
        modifié :         elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant.elmt
        modifié :         elements/10_electric/10_allpole/380_signaling&operating/11_optical_signaling/carte_voyant2.elmt
        modifié :         elements/10_electric/10_allpole/380_signaling&operating/21_selector_switches/comutator bipolar n.d.elmt
        supprimé :        elements/10_electric/10_allpole/395_electronics&semiconductors/24piezo/piezotransducer1.elmt
        supprimé :        elements/10_electric/10_allpole/395_electronics&semiconductors/24piezo/piezotransducer2.elmt
        modifié :         elements/10_electric/10_allpole/395_electronics&semiconductors/31_integrated_circuits/78xx.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/abb/abb_pfea112_ip20.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/allen_bradley/01_PLC&controllers/1734_ib8s.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/eaton_moeller/200_fuses&protective_gears/11_circuit_breakers/eaton_faz-b15_1-na.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/eaton_moeller/200_fuses&protective_gears/11_circuit_breakers/eaton_faz-c40_1-na.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/eurotherm/10_softstarters/erssw05.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/imi-ta/ta-slider_160.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/imi-ta/ta-slider_750.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/leg022118.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/leg406771.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/leg406773.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/leg406774.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/leg406775.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/legrand/qet_directory
        modifié :         elements/10_electric/20_manufacturers_articles/prominent/phmetr_prominent_dulcometer_d1c.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/raspberry/31994_0_raspeberrypib.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/raspberry/raspberry_pi_2.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/rexroth/pressure_switch_rexroth_lcd.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/rexroth/rexroth_pressure_switch_lcd.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21020.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21024.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/schneider_electric/dt40/A9N21025.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p1.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p2.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p4.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p5.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p6.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p7.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/01_PLC&controllers/6es5/6es5_95/6es5_095-8ma03__p8.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/80_building_management/n512-21.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/regul-siemens-rlu232.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/regulateur.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/siemens_6sl3000-0be23-6da1.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/siemens_6sl3000-0ce23-6aa0.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/siemens/siemens_7kt5801.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/carte_rs232.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/facade_s500.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/sofrel_4-ao.elmt
        nouveau fichier : elements/10_electric/20_manufacturers_articles/sofrel/01_PLC&controllers/s500/sofrel_4ai.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/weidmuller/tta_meroatalakito.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/wit/wit0.8.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/wit/wit2.2.3.1.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/wit/wit6.2ucentrale.elmt
        modifié :         elements/10_electric/20_manufacturers_articles/wit/witwlan.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/abb/ABB_SA_S_4.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/finder/finder60.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/finder/finder80_51.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_10A_auto.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_16A_auto.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_2A_auto.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_32A_auto.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_Prise_modulaire.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_RJ45_413003.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_eco_compteur.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_parafoudre.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/Legrand_sectionneur_63A.elmt
        modifié :         elements/10_electric/98_graphics/99_assembly_plan/01_thumbnails_mounting_plate/legrand/transformateur_modulaire.elmt
        modifié :         elements/60_energy/11_water/plomberie_chauffage/raccords_cu/codo-vuelta15.elmt
        modifié :         elements/60_energy/11_water/plomberie_chauffage/raccords_cu/tubocobre15.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/aire-agua/colector-ida.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/aire-agua/dep-inercia.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/aire-agua/intercambiador1.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/aire-agua/valv-equiibrado.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/cassette-2.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/autonomos/cassette.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/ventilacion/derivacion-te.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/ventilacion/flexible1.elmt
        modifié :         elements/60_energy/21_refrigeration/Climatizacion/ventilacion/salida-vertical.elmt
        modifié :         elements/60_energy/21_refrigeration/Frio/sinopticosfrio/controles/clixon.elmt
        modifié :         elements/60_energy/21_refrigeration/Frio/sinopticosfrio/controles/termostato-bulbo.elmt
        modifié :         examples/industrial.qet

[22:28:20] laurent@debian:~/Qet-svn/git/qet$ git commit -v
[sdeffaux-master 2a1bdf92f] Merge branch 'master' of https://github.com/sdeffaux/qelectrotech-source-mirror into sdeffaux-master
[22:30:24] laurent@debian:~/Qet-svn/git/qet$ git status
Sur la branche sdeffaux-master
rien à valider, la copie de travail est propre
[22:30:44] laurent@debian:~/Qet-svn/git/qet$ wget https://github.com/qelectrotech/qelectrotech-source-mirror/pull/15.patch
--2019-11-11 22:33:53--  https://github.com/qelectrotech/qelectrotech-source-mirror/pull/15.patch
Résolution de github.com (github.com)… 140.82.118.3
Connexion à github.com (github.com)|140.82.118.3|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://patch-diff.githubusercontent.com/raw/qelectrotech/qelectrotech-source-mirror/pull/15.patch [suivant]
--2019-11-11 22:33:54--  https://patch-diff.githubusercontent.com/raw/qelectrotech/qelectrotech-source-mirror/pull/15.patch
Résolution de patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)… 140.82.118.3
Connexion à patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)|140.82.118.3|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Un cookie provenant de patch-diff.githubusercontent.com a tenté de changer le domaine en github.com
Taille : non indiqué [text/plain]
Sauvegarde en : « 15.patch »

15.patch                                                                                             [       <=>                                                                                                                                                                                                                                                 ]   1,87M  1,35MB/s    ds 1,4s    

2019-11-11 22:33:56 (1,35 MB/s) - « 15.patch » sauvegardé [1959144]

[22:33:56] laurent@debian:~/Qet-svn/git/qet$ git am 15.patch
Application de  Update qet_directory
error: le patch a échoué : elements/10_electric/20_manufacturers_articles/schneider_electric/gb2/qet_directory:1
error: elements/10_electric/20_manufacturers_articles/schneider_electric/gb2/qet_directory : le patch ne s'applique pas
le patch a échoué à 0001 Update qet_directory
astuce: Utilisez 'git am --show-current-patch' pour visualiser le patch en échec
Quand vous avez résolu ce problème, lancez "git am --continue".
Si vous préférez plutôt sauter ce patch, lancez "git am --skip".
Pour restaurer la branche originale et arrêter de patcher, lancez "git am --abort".

**Comment by scorpio810** [comment]
https://download.tuxfamily.org/qet/scorpio/git-sdeffaux.txt

**Pull request closed without merging**
