### PR TITLE
small modifications and translations

### PR DESCRIPTION
**Pull request by plc-user**
two elements that I used for testing mirroring with QET_ElementScaler

### CODE REVIEW

**Comment by scorpio810** [comment]
Hi plc-user,
please send binary translation when you update translation, because your changes isn't visible on packages.
QET read *. qm files when you launch program and not *.ts files.

Merged, thanks

**Comment by plc-user** [comment]
Does that mean that the translations can't be used?
Where can I find comprehensible instructions on how to edit translations (on Debian unstable) so that they can be used?

**Comment by scorpio810** [comment]
On wiki you have https://qelectrotech.org/wiki_new/doc/translation
guide to use qtlinguist 
https://doc.qt.io/qt-5/linguist-translators.html

In principe just click on qet_de.ts open qtlinguist program 
`sudo apt install qttranslations5-l10n`

> This package provides translation files for Qt itself and some base apps,
> such as Qt Linguist, Qt Assistant and Qt Designer.

When you have finished translation, save and in menu file click on publish it update binary qet_de.qm file, send two files.
Because world to translate was in french in code you could open in the same windows deuch and english translation for you helping.

If you have other question, please ask, I 'm happy to help you.

**Comment by plc-user** [comment]
phew ... a rocky road for me .... ;)

To be able to work on translations for QT-Applications I had to install the package "linguist-qt6" with its dependencies from Debian-repositories.
(At least) on Debian unstable qtlinguist does not come with an executable binary in $PATH and it does not register *.ts-files for qtlinguist, so that a double-click does not start qtlinguist! To execute qtlinguist it was necessary to call it from commandline:

me@home$> /usr/lib/qt6/bin/linguist

Then it was started and I was able to open the *.ts-file and edit and "compile" the according *.qm

Thank you for the help, Laurent!

**Pull request closed without merging**
