### PR TITLE
UUID

### PR DESCRIPTION
**Pull request by Murmele**
Use uuid in the terminal instead of creating a dynamic index

### CODE REVIEW

**Comment by scorpio810** [comment]
Building in Debug mode build , but failing in Release Mode build..

**Comment by scorpio810** [comment]
[quote=De-Backer]no longer compiles from
commit ec5203253223ace22ca194b6abbe9f56f4bac76c

commit 8c6b4120f55a8f4d4916c517478413ab6cf74fd8 works

does it work for the other Qt versions?[/quote]

https://git.tuxfamily.org/qet/qet.git/commit/?id=ec5203253223ace22ca194b6abbe9f56f4bac76c

**Comment by scorpio810** [comment]
I revert again #48 
to give you time to find

**Comment by Murmele** [comment]
I see the issue for when compiling with release

**Comment by Murmele** [comment]
Ok the problem is the "inline" key in front of the definition of dockConductor().

In commit "try to use TerminalData in Terminal and PartTerminal, sou the code must not be written double" I moved the definition from the header to the source file.
Removing the "inline" key let compile the program

**Comment by Murmele** [comment]
It is building now fine in Release mode

**Comment by scorpio810** [comment]
Merged, compile fine in Release mode.
Could you rebase #49 patch
```
git am 49.patch
Application de  regarding to joshuas email, toXml uses a new structure. So it is changed in the properties interface and xrefproperties
error: le patch a échoué : sources/properties/propertiesinterface.h:34
error: sources/properties/propertiesinterface.h : le patch ne s'applique pas
error: le patch a échoué : sources/properties/xrefproperties.cpp:93
error: sources/properties/xrefproperties.cpp : le patch ne s'applique pas
error: le patch a échoué : sources/properties/xrefproperties.h:42
error: sources/properties/xrefproperties.h : le patch ne s'applique pas
error: le patch a échoué : sources/qetproject.cpp:1582
error: sources/qetproject.cpp : le patch ne s'applique pas
le patch a échoué à 0001 regarding to joshuas email, toXml uses a new structure. So it is changed in the properties interface and xrefproperties

```

**Comment by scorpio810** [comment]
```
sources/diagram.cpp:876:5: error: ‘assert’ was not declared in this scope
     assert(conductor_index == 1 || conductor_index == 2);
     ^~~~~~
sources/diagram.cpp:876:5: note: suggested alternative: ‘reset’
     assert(conductor_index == 1 || conductor_index == 2);
     ^~~~~~
     reset
```

https://launchpadlibrarian.net/484234093/buildlog_ubuntu-bionic-amd64.qelectrotech_0.80.r6376-2ubuntu1_BUILDING.txt.gz

**Comment by Murmele** [comment]
I rebased #49 the problem was that #49 was already rebased on my side. I had to revert this. Then the rebase can be done without any conflicts

**Pull request closed without merging**
