### PR TITLE
Fix build on Windows with MSVC

### PR DESCRIPTION
**Pull request by Carbenium**
Compilation using MSVC fails with a C1061 error since MSVC has a hard limit on block nesting.
Refactor the code in question to use map lookups instead.

Also add support for MSVC in MachineInfo.

### CODE REVIEW

**Comment by scorpio810** [comment]
Merged, thanks

**Comment by scorpio810** [comment]
I saw some FTBFS 
osx : 
```
lib/QtXml.framework/Headers -I/usr/local/Cellar/qt/5.15.2/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.15.2/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/kf5-kcoreaddons/5.78.0/include/KF5/KCoreAddons -I/usr/local/Cellar/qt/5.15.2/lib/QtCore.framework/Headers -Irelease -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.15.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.15.2/lib -o release/partterminal.o sources/editor/graphicspart/partterminal.cpp
make: *** [release/elementpicturefactory.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
sources/editor/graphicspart/customelementgraphicpart.cpp:1101:9: error: 
      'visit<(lambda at
      sources/editor/graphicspart/customelementgraphicpart.cpp:1101:15), const
      std::__1::variant<Qt::GlobalColor, QColor> &>' is unavailable: introduced
      in macOS 10.14
                        std::visit([&](auto&& color) { brush.setColor(co...
                             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/variant:1534:26: note: 
      'visit<(lambda at
      sources/editor/graphicspart/customelementgraphicpart.cpp:1101:15), const
      std::__1::variant<Qt::GlobalColor, QColor> &>' has been explicitly marked
      unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
sources/editor/graphicspart/customelementgraphicpart.cpp:1273:9: error: 
      'visit<(lambda at
      sources/editor/graphicspart/customelementgraphicpart.cpp:1273:15), const
      std::__1::variant<Qt::GlobalColor, QColor> &>' is unavailable: introduced
      in macOS 10.14
                        std::visit([&](auto&& color) { pen.setColor(colo...
                             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/variant:1534:26: note: 
      'visit<(lambda at
      sources/editor/graphicspart/customelementgraphicpart.cpp:1273:15), const
      std::__1::variant<Qt::GlobalColor, QColor> &>' has been explicitly marked
      unavailable here
constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                         ^
2 errors generated.
make: *** [release/customelementgraphicpart.o] Error 1

______________________________________________________________
Clean version tag:
Cleaning version tag...

make failed - 0 min 13 sec
```

Appimage on Debian Buster : 
```
 kspecs/linux-g++ -o release/eseventaddrect.o ../sources/editor/esevent/eseventaddrect.cpp
g++ -c -pipe -std=c++17 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DGIT_COMMIT_SHA=\"e9a5fded5c2e4aad7884d14d762285f12bf64673\" -DQET_LANG_PATH=/usr/local/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/local/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/local/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../qet_git -I. -I../SingleApplication -I../sources/ui -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/eseventaddterminal.o ../sources/editor/esevent/eseventaddterminal.cpp
../sources/properties/elementdata.cpp: In static member function ‘static QString ElementData::masterTypeToString(ElementData::MasterType)’:
../sources/properties/elementdata.cpp:224:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../sources/properties/elementdata.cpp: In static member function ‘static QString ElementData::slaveTypeToString(ElementData::SlaveType)’:
../sources/properties/elementdata.cpp:256:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../sources/properties/elementdata.cpp: In static member function ‘static QString ElementData::slaveStateToString(ElementData::SlaveState)’:
../sources/properties/elementdata.cpp:288:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../sources/properties/elementdata.cpp: In static member function ‘static QString ElementData::terminalTypeToString(ElementData::TerminalType)’:
../sources/properties/elementdata.cpp:320:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../sources/properties/elementdata.cpp: In static member function ‘static QString ElementData::terminalFunctionToString(ElementData::TerminalFunction)’:
../sources/properties/elementdata.cpp:352:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
g++ -c -pipe -std=c++17 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DGIT_COMMIT_SHA=\"e9a5fded5c2e4aad7884d14d762285f12bf64673\" -DQET_LANG_PATH=/usr/local/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/local/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/local/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../qet_git -I. -I../SingleApplication -I../sources/ui -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/eseventaddtext.o ../sources/editor/esevent/eseventaddtext.cpp
make[1]: *** [Makefile.Release:7185: release/elementpicturefactory.o] Error 1
make[1]: *** Attente des tâches non terminées....
../sources/editor/ui/elementpropertieseditorwidget.cpp: In member function ‘void ElementPropertiesEditorWidget::updateTree()’:
../sources/editor/ui/elementpropertieseditorwidget.cpp:163:9: warning: enumeration value ‘AllReport’ not handled in switch [-Wswitch]
  switch (type_) {
         ^
make[1] : on quitte le répertoire « /home/laurent/qet_git/build »
make: *** [Makefile:40: release] Error 2
```

Debian Bullseye : 
```
sources/factory/elementpicturefactory.cpp:915:11: error: 'visit' is not a member of 'std'
      std::visit(
           ^~~~~
sources/factory/elementpicturefactory.cpp:915:11: note: 'std::visit' is only available from C++17 onwards
sources/factory/elementpicturefactory.cpp:916:11: error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
       [&](auto&& color) { brush.setColor(color); },
           ^~~~
sources/factory/elementpicturefactory.cpp:920:37: error: 'variant' is not a member of 'std'
     static const QMap<QString, std::variant<Qt::GlobalColor, QColor>> color_style_map = {
                                     ^~~~~~~
sources/factory/elementpicturefactory.cpp:920:37: note: 'std::variant' is only available from C++17 onwards
sources/factory/elementpicturefactory.cpp:920:37: error: 'variant' is not a member of 'std'
sources/factory/elementpicturefactory.cpp:920:37: note: 'std::variant' is only available from C++17 onwards
sources/factory/elementpicturefactory.cpp:920:62: error: wrong number of template arguments (3, should be 2)
     static const QMap<QString, std::variant<Qt::GlobalColor, QColor>> color_style_map = {
                                                              ^~~~~~
In file included from /usr/include/i386-linux-gnu/qt5/QtCore/qglobal.h:1194,
                 from /usr/include/i386-linux-gnu/qt5/QtCore/qmutex.h:43,
                 from /usr/include/i386-linux-gnu/qt5/QtCore/QMutex:1,
                 from sources/factory/elementpicturefactory.h:21,
                 from sources/factory/elementpicturefactory.cpp:18:
/usr/include/i386-linux-gnu/qt5/QtCore/qtypeinfo.h:221:1: note: provided for 'template<class K, class V> class QMap'
 Q_DECLARE_MOVABLE_CONTAINER(QMap);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
sources/factory/elementpicturefactory.cpp:920:68: error: expected unqualified-id before '>' token
     static const QMap<QString, std::variant<Qt::GlobalColor, QColor>> color_style_map = {
                                                                    ^~
sources/factory/elementpicturefactory.cpp:1085:20: error: 'color_style_map' was not declared in this scope
      auto style_ = color_style_map.find(style_value);
                    ^~~~~~~~~~~~~~~
sources/factory/elementpicturefactory.cpp:1088:11: error: 'visit' is not a member of 'std'
      std::visit(
           ^~~~~
sources/factory/elementpicturefactory.cpp:1088:11: note: 'std::visit' is only available from C++17 onwards
sources/factory/elementpicturefactory.cpp:1089:11: error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
       [&](auto&& color) { pen.setColor(color); },
           ^~~~
g++ -c -pipe -std=c++17 -g -O2 -fdebug-prefix-map=/build/qelectrotech-0.90.r7388=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQET_EXPORT_PROJECT_DB -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DQET_LANG_PATH=/usr/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -ISingleApplication -Isources/ui -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtSvg -isystem /usr/include/i386-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o release/texteditor.o sources/editor/ui/texteditor.cpp
g++ -c -pipe -std=c++17 -g -O2 -fdebug-prefix-map=/build/qelectrotech-0.90.r7388=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQET_EXPORT_PROJECT_DB -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DQET_LANG_PATH=/usr/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -ISingleApplication -Isources/ui -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtSvg -isystem /usr/include/i386-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o release/eseventaddarc.o sources/editor/esevent/eseventaddarc.cpp
g++ -c -pipe -std=c++17 -g -O2 -fdebug-prefix-map=/build/qelectrotech-0.90.r7388=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQET_EXPORT_PROJECT_DB -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DQET_LANG_PATH=/usr/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -ISingleApplication -Isources/ui -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtSvg -isystem /usr/include/i386-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o release/eseventadddynamictextfield.o sources/editor/esevent/eseventadddynamictextfield.cpp
g++ -c -pipe -std=c++17 -g -O2 -fdebug-prefix-map=/build/qelectrotech-0.90.r7388=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQET_ALLOW_OVERRIDE_CED_OPTION -DQET_ALLOW_OVERRIDE_CTBTD_OPTION -DQET_ALLOW_OVERRIDE_CD_OPTION -DQET_EXPORT_PROJECT_DB -DQAPPLICATION_CLASS=QApplication -DQT_MESSAGELOGCONTEXT -DQET_LANG_PATH=/usr/share/qelectrotech/lang/ -DQET_COMMON_COLLECTION_PATH=/usr/share/qelectrotech/elements/ -DQET_COMMON_TBT_PATH=/usr/share/qelectrotech/titleblocks/ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -ISingleApplication -Isources/ui -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtSvg -isystem /usr/include/i386-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtConcurrent -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o release/eseventaddellipse.o sources/editor/esevent/eseventaddellipse.cpp
make[2]: *** [Makefile.Release:7182: release/elementpicturefactory.o] Error 1
make[2]: *** Waiting for unfinished jobs....
sources/properties/elementdata.cpp: In static member function 'static QString ElementData::masterTypeToString(ElementData::MasterType)':
sources/properties/elementdata.cpp:224:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
sources/properties/elementdata.cpp: In static member function 'static QString ElementData::slaveTypeToString(ElementData::SlaveType)':
sources/properties/elementdata.cpp:256:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
sources/properties/elementdata.cpp: In static member function 'static QString ElementData::slaveStateToString(ElementData::SlaveState)':
sources/properties/elementdata.cpp:288:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
sources/properties/elementdata.cpp: In static member function 'static QString ElementData::terminalTypeToString(ElementData::TerminalType)':
sources/properties/elementdata.cpp:320:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
sources/properties/elementdata.cpp: In static member function 'static QString ElementData::terminalFunctionToString(ElementData::TerminalFunction)':
sources/properties/elementdata.cpp:352:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
sources/editor/ui/elementpropertieseditorwidget.cpp: In member function 'void ElementPropertiesEditorWidget::updateTree()':
sources/editor/ui/elementpropertieseditorwidget.cpp:163:9: warning: enumeration value 'AllReport' not handled in switch [-Wswitch]
  switch (type_) {
         ^
make[2]: Leaving directory '/build/qelectrotech-0.90.r7388'
make[1]: *** [Makefile:40: release] Error 2
make[1]: Leaving directory '/build/qelectrotech-0.90.r7388'
dh_auto_build: make -j48 returned exit code 2
make: *** [debian/rules:8: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by scorpio810** [comment]
https://launchpadlibrarian.net/559718666/buildlog_ubuntu-bionic-i386.qelectrotech_0.90.r7388-2ubuntu1_BUILDING.txt.gz
https://launchpadlibrarian.net/559718331/buildlog_ubuntu-bionic-amd64.qelectrotech_0.90.r7388-2ubuntu1_BUILDING.txt.gz

**Comment by Carbenium** [comment]
Hmm, I assumed C++17 being the supported standard according to https://github.com/qelectrotech/qelectrotech-source-mirror/blob/e9a5fded5c2e4aad7884d14d762285f12bf64673/CMakeLists.txt#L54

So that is not the case then? What C++ version should I target for a possible solution?

**Comment by scorpio810** [comment]
I think C++11 if we want to package it for old distrib like Ubuntu bionic 
https://packages.ubuntu.com/bionic/gcc
But is strange for Debian bullseye isn't compile 
https://packages.debian.org/bullseye/gcc
And macOS with clang ...

**Comment by scorpio810** [comment]
Debian unstable build ok
Windows with MXE build ok
Flatpak build ok

**Comment by Carbenium** [comment]
https://github.com/qelectrotech/qelectrotech-source-mirror/pull/190 should fix the build failures.

**Comment by scorpio810** [comment]
Fixed, thanks you.

**Pull request closed without merging**
