### PR TITLE
snap: Port to core20 & build edge snaps on GitHub

### PR DESCRIPTION
**Pull request by ppd**
Port the snap to the core20 base and the updated kde-neon extension.

Benefits:
- newer base (core20 = 20.04)
- newer Qt. Better compatibility with xdg-desktop-portal.
- lzo compression for quicker launching

It's not possible to build with experimental extensions on launchpad right now, so also start building for edge on GitHub Actions.

There's one tiny thing that's not perfect right now, and it's still waiting for an upstream fix. This will hopefully be resolved soon, but for the moment, we simply display the update instructions attached below (only required for updates, not for new installations):
Screenshot from 2021-11-20 15-21-54

Builds on GitHub look like this: https://github.com/ppd/qelectrotech-source-mirror/runs/4273837628?check_suite_focus=true

### CODE REVIEW

**Comment by scorpio810** [comment]
It's build with my local Debian 10 SNAP builder VM?

**Comment by scorpio810** [comment]
Merged, thanks

**Comment by ppd** [comment]
Thank you, Laurent. I've added my login token to this repository as `STORE_LOGIN`. This should start building & releasing to edge on the next sync from tuxfamily.

**Comment by scorpio810** [comment]
Thanks Max for your work.
I just forced Tuxfamily to sync just now.

**Comment by ppd** [comment]
Excellent. It's already in the store.
We could also do a core20 release of 0.80 with all the nice updates. Or is 0.9 is knocking on the door already? In any case, I'd like to wait for https://github.com/snapcore/snapcraft/pull/3596 to land before we migrate stable to core20 because the users won't have to do anything manually then.

**Pull request closed without merging**
