### PR TITLE
added "company-collection" as second user-collection

### PR DESCRIPTION
**Pull request by plc-user**
- did not change Project-File, because you can build with sqlite3-support
- please check for includes of "singleapplication.h": It did not compile for me, so I had to change

### CODE REVIEW

**Comment by scorpio810** [comment]
I think your github forked isn ot up to date?

[code]diff --git a/sources/editor/graphicspart/customelementgraphicpart.cpp b/sources/editor/graphicspart/customelementgraphicpart.cpp
index 50bb4a9c5..abfa6317e 100644
--- a/sources/editor/graphicspart/customelementgraphicpart.cpp
+++ b/sources/editor/graphicspart/customelementgraphicpart.cpp
@@ -217,7 +217,8 @@ void CustomElementGraphicPart::stylesToXml(QDomElement &qde) const
         {HTMLYellowYellowFilling, "HTMLYellowYellow"},
         {HTMLYellowLightYellowFilling, "HTMLYellowLightYellow"},
         {HTMLYellowLemonChiffonFilling, "HTMLYellowLemonChiffon"},
-        {HTMLYellowLightGoldenrodYellowFilling, "HTMLYellowLightGoldenrodYellow"},
+        {HTMLYellowLightGoldenrodYellowFilling,
+         "HTMLYellowLightGoldenrodYellow"},
         {HTMLYellowPapayaWhipFilling, "HTMLYellowPapayaWhip"},
         {HTMLYellowMoccasinFilling, "HTMLYellowMoccasin"},
         {HTMLYellowPeachPuffFilling, "HTMLYellowPeachPuff"},
@@ -594,7 +595,8 @@ void CustomElementGraphicPart::stylesFromXml(const QDomElement &qde)
                 {"HTMLYellowYellow", HTMLYellowYellowFilling},
                 {"HTMLYellowLightYellow", HTMLYellowLightYellowFilling},
                 {"HTMLYellowLemonChiffon", HTMLYellowLemonChiffonFilling},
-                {"HTMLYellowLightGoldenrodYellow", HTMLYellowLightGoldenrodYellowFilling},
+                {"HTMLYellowLightGoldenrodYellow",
+                 HTMLYellowLightGoldenrodYellowFilling},
                 {"HTMLYellowPapayaWhip", HTMLYellowPapayaWhipFilling},
                 {"HTMLYellowMoccasin", HTMLYellowMoccasinFilling},
                 {"HTMLYellowPeachPuff", HTMLYellowPeachPuffFilling},
@@ -629,7 +631,8 @@ void CustomElementGraphicPart::stylesFromXml(const QDomElement &qde)
                 {"HTMLGreenChartreuse", HTMLGreenChartreuseFilling},
                 {"HTMLGreenGreenYellow", HTMLGreenGreenYellowFilling},
                 {"HTMLGreenSpringGreen", HTMLGreenSpringGreenFilling},
-                {"HTMLGreenMediumSpringGreen", HTMLGreenMediumSpringGreenFilling},
+                {"HTMLGreenMediumSpringGreen",
+                 HTMLGreenMediumSpringGreenFilling},
                 {"HTMLGreenLightGreen", HTMLGreenLightGreenFilling},
                 {"HTMLGreenPaleGreen", HTMLGreenPaleGreenFilling},
                 {"HTMLGreenDarkSeaGreen", HTMLGreenDarkSeaGreenFilling},
@@ -759,7 +762,8 @@ void CustomElementGraphicPart::stylesFromXml(const QDomElement &qde)
                 {"HTMLYellowYellow", HTMLYellowYellowColor},
                 {"HTMLYellowLightYellow", HTMLYellowLightYellowColor},
                 {"HTMLYellowLemonChiffon", HTMLYellowLemonChiffonColor},
-                {"HTMLYellowLightGoldenrodYellow", HTMLYellowLightGoldenrodYellowColor},
+                {"HTMLYellowLightGoldenrodYellow",
+                 HTMLYellowLightGoldenrodYellowColor},
                 {"HTMLYellowPapayaWhip", HTMLYellowPapayaWhipColor},
                 {"HTMLYellowMoccasin", HTMLYellowMoccasinColor},
                 {"HTMLYellowPeachPuff", HTMLYellowPeachPuffColor},[/code]

I don't understand this patch?
[quote]diff --git a/sources/editor/graphicspart/partterminal.cpp b/sources/editor/graphicspart/partterminal.cpp
index dc1a68101..c46c2dc96 100644
--- a/sources/editor/graphicspart/partterminal.cpp
+++ b/sources/editor/graphicspart/partterminal.cpp
@@ -176,6 +176,7 @@ qreal PartTerminal::rotation() const {
 		case Qet::South : return 180;
 		case Qet::West  : return 270;
 	}
+    return 0;
 }[/quote]

Same here for these patch

[code]diff --git a/sources/properties/elementdata.cpp b/sources/properties/elementdata.cpp
index 309e98593..6209fb85d 100644
--- a/sources/properties/elementdata.cpp
+++ b/sources/properties/elementdata.cpp
@@ -362,6 +362,7 @@ QString ElementData::masterTypeToString(ElementData::MasterType type)
         case ElementData::Commutator:
             return QStringLiteral("commutator");
     }

**Comment by scorpio810** [comment]
Please remove in your PR these patchs:
/sources/utils/macosxopenevent.cpp
/sources/qetgraphicsitem/qetshapeitem.cpp
/sources/properties/elementdata.cpp
/sources/editor/graphicspart/partterminal.cpp
/sources/editor/graphicspart/customelementgraphicpart.cpp

**Comment by scorpio810** [comment]
If you can't plc-user, just ask me, I think I can hacks your patch or delete not usefull parts patch in Github GUI...

I just want to see only the necessary changes, but not other modified files which have nothing to do with it, then to find a malfunction in 6 months or in a year it will be an ordeal to find the guilty commit..

Sorry if I'm being harsh, but that's how good work should be done.

Cheers,
Laurent

**Comment by plc-user** [comment]
You are absolutely right, Laurent!

I should not mix other changes into this functional extension!

git / github and me aren't friends ... yet!  ;)
It seems that the named files are removed from this pull-request.

**Comment by scorpio810** [comment]
Thanks for your patience, Plc-user!

Another tip please use tabulation and not speace. ;-)

https://qelectrotech.org/wiki_new/doc/qt_creator#on_ajoute_le_style_de_code_qet

**Comment by xavierog** [comment]
Hi @plc-user,

I am the former developer of the QElectroTech project. Though I no longer contribute to the project, I heard about this PR and I must say I am a little surprised since it aims to cover a use case that QElectroTech has handled almost since its birth.
Namely, we had the concept of "company collection" in mind since the very beginning and this is how the "common collection" vs "custom collection" distinction was born. The idea was to allow QElectroTech to take arbitrary directories as common collection. This can be achieved by various means and, unlike what I read on the forum, it absolutely does not require any symlink.

The available mechanisms are:

- at compile time: there is a variable that embeds the default path into the `qelectrotech` / `qelectrotech.exe` executable -- but that is definitely not very convenient (it was meant for packagers)
- at run time: there is a `--common-elements-dir=DIR` command-line option; on any OS (including Windows), adding this option inside a standard Windows shortcut (*.lnk) can easily turn QElectroTech into whatever your company desires.
- Note: there is also a `--common-tbt-dir=DIR` option to make your company's official title blocks available to everyone.
- as mentioned on the forum, it is also possible to set this through the User Interface in Settings > Configure > Collections but I understand this can be more difficult to apply/deploy on all workstations.

So, typically, and even though this is not very well documented, your company could deliver both the QET collection and their own elements (+ titleblocks) to their end users just by providing a shared directory with both collections and deploying QET with `--common-elements-dir=<path to the shared directory>`. All of it without having to touch a single line of C++ and without a single symlink.
Of course, it DOES require to customize the way QET is launched (shortcut or .bat file), but this is usually WAY easier than swimming in VMs, compilers and C++ to implement a third collection.

Consequently, I would like to know the exact enterprise setup that pushed you towards this path. Can you tell us how QET is deployed in your company so we get a better idea of **why** this feature is a must-have? If necessary, we can take this conversation to a private medium, thus ensuring you do not say too much about your company's internal practices.

A bit of extra context: I am *NOT* here to deny your pull request. But I do know that we lack official documentation explaining how to deploy QElectroTech within a company, and I suspect there is a deep misunderstanding. And if it turns out `--common-elements-dir=` is not enough to make QElectroTech enterprise-friendly, then we can reassess the situation based on your exact use case and get back to this PR.

**Comment by scorpio810** [comment]
@plc-user : 
https://qelectrotech.org/forum/viewtopic.php?pid=19284#p19284

**Comment by plc-user** [comment]
I had hoped to have this discussion in the QET forum more than two years ago and not after so long and when much of the work for this functionality is already done!

Still, we should not have the discussion on github, but on the QET forum (https://qelectrotech.org/forum/viewtopic.php?id=2105) so that QET users who don't necessarily have an account here can participate and benefit.

**Pull request merged**
