### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by pkess**
Hello,

i added and changed some translations for the terminal editor to german.

### CODE REVIEW

**Comment by scorpio810** [comment]
Hello,
many thanks, but I saw a little conflits, you could fix it?
https://github.com/qelectrotech/qelectrotech-source-mirror/pull/225/conflicts

**Comment by pkess** [comment]
I am sorry. I already fixed the merge conflicts but forgot to push the update

**Comment by scorpio810** [comment]
Hmm

```
laurent@debian:~/Qet-svn/git/qet$ git am 225.patch 
Application de  Add german translations
error: le patch a échoué : lang/qet_de.ts:12373
error: lang/qet_de.ts : le patch ne s'applique pas
l'application de la rustine a échoué à 0001 Add german translations
astuce: Utilisez 'git am --show-current-patch=diff' pour visualiser le patch en échec
Quand vous avez résolu ce problème, lancez "git am --continue".
Si vous préférez plutôt sauter ce patch, lancez "git am --skip".
Pour restaurer la branche originale et arrêter de patcher, lancez "git am --abort".
```

**Comment by pkess** [comment]
I am sorry. I am not really familiar in working with patches. I think the Point here is the merge from master into this feature i created. 
I pushed a new branch called "translations_german2". Maybe you can use this?

**Comment by scorpio810** [comment]
Make a PR of branche translations_german2 and I try to merge it.

**Pull request closed without merging**
