### PR TITLE
Fix various typos in source documentation and comments (cont.)

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by scorpio810** [comment]
```
git am 237.patch 
Application de  Fix various typos in source documentation and comments (cont.)
erreur : le patch a échoué : build-aux/windows/QET.nsi:261
erreur : build-aux/windows/QET.nsi : le patch ne s'applique pas
erreur : le patch a échoué : build-aux/windows/QET64.nsi:266
erreur : build-aux/windows/QET64.nsi : le patch ne s'applique pas
l'application de la rustine a échoué à 0001 Fix various typos in source documentation and comments (cont.)
astuce: Utilisez 'git am --show-current-patch=diff' pour visualiser le patch en échec
Quand vous avez résolu ce problème, lancez "git am --continue".
Si vous préférez plutôt sauter ce patch, lancez "git am --skip".
Pour restaurer la branche originale et arrêter de patcher, lancez "git am --abort".
```

**Comment by scorpio810** [comment]
```
diff --git a/build-aux/windows/QET.nsi b/build-aux/windows/QET.nsi
index 721ec73b46..7c73665fb0 100644
--- a/build-aux/windows/QET.nsi
+++ b/build-aux/windows/QET.nsi
@@ -261,13 +261,13 @@ Section ""
 	; write file associations registry keys
 	WriteRegStr   HKEY_CLASSES_ROOT "Applications\qelectrotech.exe\shell\open\command" ""             "$\"$final_qet_exe$\" $\"%1$\""
 	WriteRegStr   HKEY_CLASSES_ROOT ".qet"                                             ""             "qet_diagram_file"
-	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file"                                 ""             "Schéma QET"
+	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file"                                 ""             "Schï¿œma QET"
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_diagram_file"                                 "EditFlags"    0x00000000
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_diagram_file"                                 "BrowserFlags" 0x00000008
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file\DefaultIcon"                     ""             "$final_project_ico"
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file\shell\open\command"              ""             "$\"$final_qet_exe$\" $\"%1$\""
 	WriteRegStr   HKEY_CLASSES_ROOT ".elmt"                                            ""             "qet_element_file"
-	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file"                                 ""             "Élément QET"
+	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file"                                 ""             "ï¿œlï¿œment QET"
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_element_file"                                 "EditFlags"    0x00000000
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_element_file"                                 "BrowserFlags" 0x00000008
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file\DefaultIcon"                     ""             "$final_element_ico"
@@ -342,7 +342,7 @@ FunctionEnd
 ;--------------------------------
 ;Descriptions
 
-	;USE A LANGUAGE STRING IF YOU WANT YOUR DESCRIPTIONS TO BE LANGAUGE SPECIFIC
+	;USE A LANGUAGE STRING IF YOU WANT YOUR DESCRIPTIONS TO BE LANGUAGE SPECIFIC
 
 	;Assign descriptions to sections
 	;!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
diff --git a/build-aux/windows/QET64.nsi b/build-aux/windows/QET64.nsi
index b13e7db845..a800402448 100644
--- a/build-aux/windows/QET64.nsi
+++ b/build-aux/windows/QET64.nsi
@@ -266,13 +266,13 @@ Section ""
 	; write file associations registry keys
 	WriteRegStr   HKEY_CLASSES_ROOT "Applications\qelectrotech.exe\shell\open\command" ""             "$\"$final_qet_exe$\" $\"%1$\""
 	WriteRegStr   HKEY_CLASSES_ROOT ".qet"                                             ""             "qet_diagram_file"
-	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file"                                 ""             "Schéma QET"
+	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file"                                 ""             "Schï¿œma QET"
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_diagram_file"                                 "EditFlags"    0x00000000
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_diagram_file"                                 "BrowserFlags" 0x00000008
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file\DefaultIcon"                     ""             "$final_project_ico"
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_diagram_file\shell\open\command"              ""             "$\"$final_qet_exe$\" $\"%1$\""
 	WriteRegStr   HKEY_CLASSES_ROOT ".elmt"                                            ""             "qet_element_file"
-	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file"                                 ""             "Élément QET"
+	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file"                                 ""             "ï¿œlï¿œment QET"
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_element_file"                                 "EditFlags"    0x00000000
 	WriteRegDWORD HKEY_CLASSES_ROOT "qet_element_file"                                 "BrowserFlags" 0x00000008
 	WriteRegStr   HKEY_CLASSES_ROOT "qet_element_file\DefaultIcon"                     ""             "$final_element_ico"
@@ -355,7 +355,7 @@ FunctionEnd
```

**Comment by scorpio810** [comment]
I removed in  file patch QET.nsi and QET64.nsi
Merged, thanks

**Comment by luzpaz** [comment]
Sorry about the delay, i couldn't get to it until now. Are you planning to add the typo change manually for the above `.nsi` files and also for  `sources/createdxf.cpp` (line 944 `s/Conveniance/Convenience/`) ?

**Pull request closed without merging**
