### PR TITLE
Multi edit element editor

### PR DESCRIPTION
**Pull request by Murmele**
Add ability to edit multiple parts at the same time

### CODE REVIEW

**Comment by Murmele** [comment]
I rebased it on the current master

**Comment by scorpio810** [comment]
Try again to rebase it I forced Github clone to sync to master

**Comment by Murmele** [comment]
I did

**Comment by scorpio810** [comment]
Great!
And what about join team?
https://qelectrotech.org/wiki_new/doc/rejoin_project

**Pull request closed without merging**
