### PR TITLE
Fix various source typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by scorpio810** [comment]
Hi Luzpaz, source comment in code for translations was in french, don't translate them.

**Comment by scorpio810** [comment]
```
git am 239.patch 
Application de  Fix source typo 'Rigth'
Application de  Fix source typo 'minimumRowHeigth'
Application de  Fix source typo 'cross_min_heigth'
Application de  Fix source typo 'Hidding'

```

Merged, thanks

**Comment by scorpio810** [comment]
@luzpaz  are you Kunda1 on freeCAD forum?
BTW, a QET guy ask me to add 3Dmouse support on 2D QET, but I don't know how to start, I saw freeCAD support it.
https://qelectrotech.org/forum/viewtopic.php?pid=15941#p15941

**Comment by luzpaz** [comment]
Yes, that's me on the FC forum.

**Pull request closed without merging**
